Feature/automatically fill playerid when joining a match
boardgameio/boardgame.io pull request #1013
Opened 2021-09-23 10:14 UTC by liorp

#### Checklist

- [✅] Use a separate branch in your local repo (not `main`).
- [✅ ] Test coverage is 100% (or you have a story for why it's ok).

Solves #1012

2021-10-01 13:37 UTC, delucis requested changes
Hey @liorp — sorry it took me a while to get to this. Thanks for putting it together. This mostly looks really good, so the comments are more small details.

One other thing we should change is [the lobby client](https://github.com/boardgameio/boardgame.io/blob/main/src/lobby/client.ts), which helps with making API requests. The client does some pre-validation and currently expects `playerID` to be provided for join requests so we should loosen that requirement. Let me know if you think you can do that, otherwise I can probably find time to make that change.

2021-10-01 13:57 UTC, liorp commented on src/server/api.ts
> +        );
I wanted to show the number of players in the error too - thought it would be more convenient than to show it from the metadata

2021-10-01 14:00 UTC, liorp commented on src/server/util.ts
> +  Math.max(...Object.keys(players).map((k) => Number.parseInt(k))) + 1;
I thought about a scenario in which there are maximum 3 players, and one player left. Shouldn't length be reported as 2 in this case?

2021-10-01 14:10 UTC, delucis commented on src/server/util.ts
> +  Math.max(...Object.keys(players).map((k) => Number.parseInt(k))) + 1;
I don’t think so, but I’m also not sure the `Math.max` version would return something different?

Players looks like `{ 0: {...}, 1: {...}, 2: {...} }`, so in your case you’d get `max(0, 1, 2) + 1`. When a player uses the `leave` endpoint we don’t remove their seat, we just make it available for someone else to take (or for them to rejoin), so the number of players in the `players` object stays the same.

2021-10-01 14:16 UTC, delucis commented on src/server/api.ts
> +        );
OK, if you need it, we can leave it. I thought if a client is just requesting the next available slot, the exact number of players might not be so relevant.

2021-10-01 14:25 UTC, liorp commented on src/server/util.ts
> +  Math.max(...Object.keys(players).map((k) => Number.parseInt(k))) + 1;
Right. I had something different in mind 😅

2021-10-01 14:25 UTC, liorp commented
Working on tests...

2021-10-01 14:27 UTC, delucis commented
@liorp If you mean because of the failing CI, I think that’s just linter errors. Try running `npm run prettier`.

2021-10-01 14:33 UTC, liorp commented
It doesn't run... says something about `Error: Could not locate the bindings file. Tried:`. Trying to reinstall packages, will report shortly

2021-10-01 14:50 UTC, delucis commented
> It doesn't run... says something about `Error: Could not locate the bindings file. Tried:`. Trying to reinstall packages, will report shortly

Sounds like you may have run `npm install` and then changed the version of Node. `npm install` should get that back working.

2021-10-01 17:46 UTC, liorp commented
Oh, skipped the part about the lobby api. Probably wouldn’t be able to work on this for a while. Is this blocking?

2021-10-01 23:18 UTC, delucis commented
> Oh, skipped the part about the lobby api. Probably wouldn’t be able to work on this for a while. Is this blocking?

Would be best to keep them in sync, but I can take care of that side of things.

2021-10-02 00:08 UTC, delucis approved these changes

2021-10-02 00:09 UTC, merged